### PR TITLE
Check if experiment_id attribute is present in current dataset when being processed by PrePARE

### LINKED ISSUE #643: PrePARE UnicodeDecodeError when scanning dummy NO_ATTRIBUTES.nc netCDF file
Hello, 
when exploring how the PrePARE checker is working, I tried it out on various files. 
While it works perfectly on a ps_3hr_MPI-ESM1-2-HR_historical_r6i1p1f1_gn_201007120000-201007122100.nc file, there is a strange UnicodeDecodeError when using it for scanning the dummy netcdf file https://raw.githubusercontent.com/AtMoDat/demo_data/main/NO_ATTRIBUTES.nc.

```
PrePARE.py --variable ps NO_ATTRIBUTES.nc --table-path /pool/data/CMIP6/cmip6-cmor-tables/Tables/CMIP6_3hr.json
Traceback (most recent call last):
  File "/mnt/lustre01/work/bm0021/conda-envs/quality-assurance/lib/python3.9/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 1022, in <module>
    main()
  File "/mnt/lustre01/work/bm0021/conda-envs/quality-assurance/lib/python3.9/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 935, in main
    log_text = f.read()
  File "/mnt/lustre01/work/bm0021/conda-envs/quality-assurance/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 18771: invalid start byte
```

The dummy file is a netCDF file with no metadata, but otherwise a valid netCDF file. 
E.g. output when scanning with the latest CEDA CF Checker
```
cfchecks NO_ATTRIBUTES.nc
CHECKING NetCDF FILE: NO_ATTRIBUTES.nc
=====================
Using CF Checker Version 4.1.0
Checking against CF Version CF-1.8
Using Standard Name Table Version 78 (2021-09-21T11:55:06Z)
Using Area Type Table Version 10 (23 June 2020)
Using Standardized Region Name Table Version 4 (18 December 2018)
[...]
ERRORS detected: 0
WARNINGS given: 9
INFORMATION messages: 2

```
Thanks and best regards

### PR DESCRIPTION
**Pull request by mauzey1**
Fixes #643

### CODE REVIEW

**Review by durack1 — APPROVED** [review]
@mauzey1 thanks for catching this - @matthew-mizielinski are there any other obvious tweaks you suggest?

**Review by piotr-florek-mohc — APPROVED** [review]
Looks good to me.

**Comment by piotr-florek-mohc** [comment]
Just a quick note, this fix doesn't appear to resolve the whole issue raised in #643 entirely (at least it didn't do it for me), as there are other problems with the netCDF file, which cmor to fail because of weird characters appearing in the log file. The quick fix, as commented by @matthew.mizielinski, is to provide encoding parameter to the `PrePARE.py` script.

```
diff --git a/LibCV/PrePARE/PrePARE.py b/LibCV/PrePARE/PrePARE.py
index 6fcd570..97f1c9e 100755
--- a/LibCV/PrePARE/PrePARE.py
+++ b/LibCV/PrePARE/PrePARE.py
@@ -931,7 +931,7 @@ def main():
         remove_ansi = re.compile(r'\x1b\[[0-?]*[ -/]*[@-~]')
         for logfile in set(logfiles):
             if not os.stat(logfile).st_size == 0:
-                with open(logfile, 'r') as f:
+                with open(logfile, 'r', encoding='utf8', errors='ignore') as f:
                     log_text = f.read()
                     if args.no_text_color:
                         log_text = remove_ansi.sub('', log_text)
@@ -955,7 +955,7 @@ def main():
             logfile, rc = process(source)
             errors += rc
             if not os.stat(logfile).st_size == 0:
-                with open(logfile, 'r') as f:
+                with open(logfile, 'r', encoding='utf8', errors='ignore') as f:
                     log_text = f.read()
                     if args.no_text_color:
                         log_text = remove_ansi.sub('', log_text)
```

**Comment by mauzey1** [comment]
@piotr-florek-mohc 

Okay, I have added the suggested changes to PrePARE.  I would still like to keep finding bugs in CMOR_CV code similar to the ones I have found, but this will at least reduce the chances of PrePARE crashing when processing erroneous NetCDF files.

**Comment by durack1** [comment]
@mauzey1 @piotr-florek-mohc (and @matthew-mizielinski) thanks for this tweak!

**Comment by mauzey1** [comment]
The MacOS Python 3.9 check failed due to a server error with conda.  The last change committed wouldn't not have affected the tests anyway.  I will merge this now.

**Pull request merged**
