### PR TITLE
Set global attributes with values from registered content if they are not found in user input

### LINKED ISSUE #628: Cleaning up CMOR input file vs registered content sources
@mauzey1 I have been trying to simplify my [CMOR_input.json](https://github.com/PCMDI/amipbcs/blob/master/CMOR/drive_input4MIPs_obs.json) file along with the details (that are currently duplicated) in the registered content, found in the [input4MIPs_CV.json](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/issue87_durack1_PCMDI-AMIP-1-2-0AndPy3Update/Tables/input4MIPs_CV.json#L974-L1007) file.

My aspiration, was that all information that is contained in the registered content (`input4MIPs_CV.json`) would be the primary source, and only additional/runtime info e.g.

Screen Shot 2021-09-02 at 1 28 28 PM
[link](https://github.com/PCMDI/amipbcs/blob/ac641dfa1bee45d4b259e891f06ca7e98b8734ea/CMOR/drive_input4MIPs_obs.json#L15-L27)

Would be included in the `CMOR_input.json` file, whereas all registered content would be used by default, and if there was an additional definition of the variable with the same name in the `CMOR_input.json` then this would overwrite the `input4MIPs_CV.json` sourced entry.

Can you comment on this?

@taylor13 ping

### PR DESCRIPTION
**Pull request by mauzey1**
Resolves #628

### CODE REVIEW

**Comment by mauzey1** [comment]
@durack1 I just wanted to know if you have any questions about this PR, or whether or not there is something that I haven't addressed with this PR.

**Review by durack1 — APPROVED** [review]
@mauzey1 apologies, I had missed this - any other showstopper PRs that need prompt merging?

**Comment by durack1** [comment]
@mauzey1 will this be pushed to the conda testing channel? If yes, great, I can dig up my test codes within input4MIPs to make sure that the issue is solved

**Comment by mauzey1** [comment]
@durack1 It was already in the testing channel.  It will now be built into the nightly build as well.

**Comment by durack1** [comment]
@mauzey1 excellent, so I assume a new build (dated ~now) will show up on https://anaconda.org/PCMDI/cmor/files by tomorrow?

**Pull request merged**
