### PR TITLE
Cmor grid vertices charles

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by wachsylon** [comment]
Hi,
what is the problem with this branch? Can I help somehow to get this done?
Best regards,
Fabi

**Comment by doutriaux1** [comment]
@mauzey1 do you mind taking a look? Thanks.

**Comment by mauzey1** [comment]
@doutriaux1 @wachsylon There were problems with the conda install of Python that were breaking the continuous integration tests.  They seem to be resolved now.

**Comment by doutriaux1** [comment]
@mauzey1 yes if tests pass please merge in

**Pull request merged**
