### PR TITLE
Make git ignore build-generated and test-generated files

### PR DESCRIPTION
**Pull request by mauzey1**
These changes will make git ignore build files and tests executables.  They also change some tests that were creating their own tables and log files.  The tests will now delete their generated tables when they are done with them, and will no longer generate log files.

### CODE REVIEW

**Comment by taylor13** [comment]
Was there no useful information in the log files?  Just wondering.

**Comment by mauzey1** [comment]
@taylor13 The log file was storing the execution times for cmor and cdms2 for different deflate and shuffle values.  These values were already being printed to the console.  I could make the tests output a log file again but with a flag that prevents it from being created by default.

**Comment by taylor13** [comment]
o.k. thanks for explaining.  Thanks for cleaning things up.

**Comment by mauzey1** [comment]
@doutriaux Could you review this PR?  Thank you.

**Comment by mauzey1** [comment]
@durack1 I could also add @sterlingbaldwin but his name doesn't appear in the list of reviewers for CMOR.

**Comment by durack1** [comment]
@mauzey1 let's fix that, @sterlingbaldwin was just added. You're a repo admin so you should be able to manage the repo users - I also wonder whether we still need access for @dnadeau4 and wachslyon?

**Comment by mauzey1** [comment]
@durack1 @dnadeau4 has left PCMDI but @wachsylon occasionally contributes to this project.

**Pull request merged**
