### PR TITLE
Append mode for associated variables

### PR DESCRIPTION
**Pull request by wachsylon**
Initialize the correct time_bounds for a auxiliary variable when applying CMOR in append mode

### CODE REVIEW

**Comment by wachsylon** [comment]
See #235

**Comment by doutriaux1** [comment]
@wachsylon thanks for this, will review and merge tomorrow.

**Comment by doutriaux1** [comment]
@wachsylon could you setup your fork to trigger circleci (and possibly) travis tests?

**Comment by doutriaux1** [comment]
got it to trigger with master in at: https://github.com/PCMDI/cmor/pull/378

**Comment by doutriaux1** [comment]
@wachsylon do you mind adding a test for this? Or send me one so I add it to the code. Thanks.

**Pull request closed without merging**
