### PR TITLE
Replace listserv email

### LINKED ISSUE #652: Update CMOR mailing list email address
The following is thrown when an error is caught:
```python
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The source_id, "PCMDI-AMIP-1-2-0",  which you specified in your 
! input file could not be found in 
! your Controlled Vocabulary file. (./CMOR/input4MIPs-cmor-tables/Tables/input4MIPs_CV.json) 
! 
! Please correct your input file or contact cmor@listserv.llnl.gov to register
! a new source.   
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

We should probably change this email address, which most likely won't work - has this mailing list been updated yet?

### LINKED ISSUE #659: Add BSD-3 license to repo
A BSD-3 license has been applied to the cmip6-cmor-tables repo see https://github.com/PCMDI/cmip6-cmor-tables/issues/374, should the unusual CCLRC license be updated here?

@taylor13 @mauzey1 @matthew-mizielinski

### PR DESCRIPTION
**Pull request by mauzey1**
Resolves #652 
Resolves #659 

Replaces `cmor@listserv.llnl.gov` with `pcmdi-cmip@llnl.gov` for registering controlled vocabulary values.

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 thanks for this, I had thought about changing this. I am wondering whether we list the repos specifically (e.g. https://github.com/WCRP-CMIP/CMIP6_CVs, etc), or just have the single mailing list address.

@taylor13 do you have any firm thoughts on this?

**Comment by taylor13** [comment]
Not sure.  Do we currently have multiple CMIP mailing lists?  I think the CMOR list should definitely be separate from the CV list.

**Comment by durack1** [comment]
@taylor13 across PCMDI-affiliated projects, we're using CMOR across CMIP6 ([CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs), [input4MIPs](https://github.com/PCMDI/input4MIPs-cmor-tables) and [obs4MIPs](https://github.com/PCMDI/obs4MIPs-cmor-tables)), but CMOR is being used across a far-broader range of projects. The pcmdi-cmip mailing list is a grab all for directions. @matthew-mizielinski, any suggestions?

**Comment by durack1** [comment]
@matthew-mizielinski, the complication is that we have at least 3 projects that have PCMDI leadership, and many that don't, and so I had thought that we should just list the issue pages of repos, this isn't going to capture everything. Not sure if we have another way to address this, other than field queries through a mailing list.

RE: joining, sure, I'll add you

**Comment by durack1** [comment]
@matthew-mizielinski how about this for a suggestion, we include the mailing list, PLUS also add the URL to our table listing https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel//cmor_and_mip_tables.html (minus the duplicate `//`)

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski how about this for a suggestion, we include the mailing list, PLUS also add the URL to our table listing https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel//cmor_and_mip_tables.html (minus the duplicate `//`)

Sounds good to me

**Review by durack1 — APPROVED** [review]
@mauzey1 apologies for this sitting in the queue too, not sure how I missed it

**Comment by durack1** [comment]
@mauzey1 would the addition of the wcrp-cmip HTML page break things, regarding 1023+ string sizes? If no, then I think we want to add this additional info as a point of reference for users to help themselves

**Comment by mauzey1** [comment]
@durack1 Would this error message work?
```
C Traceback:
! In function: _CV_checkSourceID
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The source_id, "wrong_id",  which you specified in your 
! input file could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid source_id from the CV of your MIP tables 
! listed at https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel//cmor_and_mip_tables.html, 
! or contact pcmdi-cmip@llnl.gov to register a new source.   
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by mauzey1** [comment]
Similar for the institution_id

```
C Traceback:
! In function: _CV_setInstitution
! called from: cmor_setGblAttr
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The institution_id, "wrong_id",  found in your 
! input file (Test/CMOR_input_example.json) could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid institution_id from the CV of your MIP tables 
! listed at https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel//cmor_and_mip_tables.html, 
! or contact "pcmdi-cmip@llnl.gov" to register a new institution_id.  
! 
! See "http://cmor.llnl.gov/mydoc_cmor3_CV/" for further information about
! the "institution_id" and "institution" global attributes.  
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by durack1** [comment]
@mauzey1 thanks for following up on this. How about:

```
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The institution_id, "wrong_id",  found in your 
! input file (Test/CMOR_input_example.json) could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid institution_id listed in your MIP tables CV file.
! To add a new institution_id to the Tables/<Project>_CV.json file, open a new issue in the
! table Github repository. Managed project CMOR and MIP tabled are listed at
! https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/cmor_and_mip_tables.html, 
! or contact "pcmdi-cmip@llnl.gov" for additional guidance.  
! 
! See "http://cmor.llnl.gov/mydoc_cmor3_CV/" for further information about
! the "institution_id" and "institution" global attributes.  
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by mauzey1** [comment]
@durack  Here are the updated error messages.  Did you also want users to add new sources by opening GitHub issues?

```
C Traceback:
! In function: _CV_checkSourceID
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The source_id, "wrong_id",  which you specified in your 
! input file could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid source_id listed in your MIP tables' CV file. 
! Managed project CMOR and MIP tables are listed at 
! https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel//cmor_and_mip_tables.html, 
! Contact pcmdi-cmip@llnl.gov to register a new source.   
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

```
C Traceback:
! In function: _CV_setInstitution
! called from: cmor_setGblAttr
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The institution_id, "wrong_id",  found in your 
! input file (Test/CMOR_input_example.json) could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid institution_id listed in your MIP tables' CV file.
! To add a new institution_id to the Tables/CMIP6_CV.json file, open a new issue in the
! table's Github repository. Managed project CMOR and MIP tables are listed at
! https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/cmor_and_mip_tables.html. 
! Contact "pcmdi-cmip@llnl.gov" for additional guidance.  
! 
! See "http://cmor.llnl.gov/mydoc_cmor3_CV/" for further information about
! the "institution_id" and "institution" global attributes.  
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by durack1** [comment]
@mauzey1 thanks for catching the source_id too, how about we replace this with (the identical text, switching out `institution*` with `source*`:

```
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The source_id, "wrong_id," found in your 
! input file (Test/CMOR_input_example.json) could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid source_id listed in your MIP tables' CV file.
! To add a new source_id to the Tables/CMIP6_CV.json file, open a new issue in the
! table's Github repository. Managed project CMOR and MIP tables are listed at
! https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/cmor_and_mip_tables.html. 
! Contact "pcmdi-cmip@llnl.gov" for additional guidance.  
! 
! See "http://cmor.llnl.gov/mydoc_cmor3_CV/" for further information about
! the "source_id" and "source" global attributes.  
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

Note the extraneous space I removed in `"wrong_id",  found`

**Comment by mauzey1** [comment]
@durack1 The new error messages

```
C Traceback:
! In function: _CV_setInstitution
! called from: cmor_setGblAttr
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The institution_id, "wrong_id", found in your 
! input file (Test/CMOR_input_example.json) could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid institution_id listed in your MIP tables' CV file.
! To add a new institution_id to the Tables/CMIP6_CV.json file, open a new issue in the
! table's Github repository. Managed project CMOR and MIP tables are listed at
! https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/cmor_and_mip_tables.html. 
! Contact "pcmdi-cmip@llnl.gov" for additional guidance.  
! 
! See "http://cmor.llnl.gov/mydoc_cmor3_CV/" for further information about
! the "institution_id" and "institution" global attributes.  
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: _CV_checkSourceID
! called from: cmor_setGblAttr
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The source_id, "wrong_id", found in your 
! input file (Test/CMOR_input_example.json) could not be found in 
! your Controlled Vocabulary file. (Tables/CMIP6_CV.json) 
! 
! Please correct your input file by using a valid source_id listed in your MIP tables' CV file.
! To add a new source_id to the Tables/CMIP6_CV.json file, open a new issue in the
! table's Github repository. Managed project CMOR and MIP tables are listed at
! https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/cmor_and_mip_tables.html. 
! Contact "pcmdi-cmip@llnl.gov" for additional guidance.  
! 
! See "http://cmor.llnl.gov/mydoc_cmor3_CV/" for further information about
! the "source_id" and "source" global attributes.  
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

Resolves #659

**Comment by durack1** [comment]
@mauzey1 excellent, this looks great

**Pull request merged**
