### PR TITLE
Some improvements and bugfixes

### PR DESCRIPTION
**Pull request by glevava**
This PR:
- solves the "memory" effect from `cmip6.set_CV_error()` while checking several files in a bulk. It has been replace by a `self.cv_error` variable reinitialized when instanciated.
- supports the "OR" logic operator for `cell_measures` attributes from CMOR tables.
- rewrites code following most of PEP008 convention.

### CODE REVIEW

**Comment by durack1** [comment]
@glevava it seems there are some merge conflicts - can you rebase off master?

**Comment by glevava** [comment]
@durack1 @dnadeau4  I fix conflicts with the cmor/PrePARE branch. Ready for merging after your review of course. Thanks !

**Comment by dnadeau4** [comment]
Ok Thanks, I was ready to do that today.  👍

**Comment by durack1** [comment]
@glevava thanks! @dnadeau4 great, thanks!

**Comment by taylor13** [comment]
see also my comment at: https://github.com/PCMDI/cmor/issues/314#issuecomment-373102241

concerning the treatment of parenthetical information in cell_methods.  This information is both optional and does not have to follow any rules, so we don't want to check it.  I think that @glevava 's revisions should handle this properly, but others should double check before accepting.

thanks, @glevava, for these valuable contributions.

**Comment by durack1** [comment]
@glevava it seems this PR has carried along a bunch of your personal files, along with merge conflicts too - eek! Take a look [here](https://github.com/PCMDI/cmor/pull/315/files)

**Comment by glevava** [comment]
Arg ! Misconfigured .gitignore.
Let me fix that. Anyway, only PrePARE.py should be reviewed.
All the rest is only matter of merging. In addition, on which branch should we pull request for PrePARE? Is "PrePARE" branch the appropriate one?

**Comment by durack1** [comment]
@glevava I believe that is correct, but I will defer to @dnadeau4 ?

**Comment by glevava** [comment]
yes, ok. @dnadeau4 let me know if I need to pull a new request or if can do the cleanup on your side. Thanks

**Comment by dnadeau4** [comment]
There are a lot of files that I don't need.  You also merged the conflicts in PrePARE.py.  I'll do the clean up today and merge.  I just have to checkout your https://github.com/PCMDI/cmor/pull/315/commits/3fb68c21f16f893f270fde0c6ba7083691492383 commit.  (I think..)

**Comment by glevava** [comment]
ok thanks ! Indeed a lot of files comes from my IDE.

**Comment by dnadeau4** [comment]
I will was able to merge and will make my own PR.  Thanks!

**Pull request closed without merging**
