### PR TITLE
Allow axis values to be within 1.e-6 fractional error of the valid_min and valid_max

### PR DESCRIPTION
**Pull request by mauzey1**
#495 
Allow axis values within a fractional error of the valid_min or valid_max of an axis.  This is designed to allow values that are meant to be the min or max of an axis but have been converted from floats to doubles.

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 I am about to take off on international travel and then some vacation, for PRs over the next couple of weeks, I suggest pinging @taylor13 alone for a code review

**Comment by taylor13** [comment]
As we discussed, we should change the "<" to "<=" and ">" to ">=".  Otherwise, when the min or max value is 0 and the user-passed value is 0, the code will raise an error when the value of 0 is perfectly acceptable.

**Comment by mauzey1** [comment]
@taylor13 These lines are meant to detect when the value goes beyond the threshold, so they shouldn't raise an error when the value and the min/max are zero.
https://github.com/PCMDI/cmor/blob/a246d1d0eb6cf5f5f42920d951c0564e06233b8a/Src/cmor_axes.c#L1196-L1211
https://github.com/PCMDI/cmor/blob/a246d1d0eb6cf5f5f42920d951c0564e06233b8a/Src/cmor_axes.c#L1222-L1225
https://github.com/PCMDI/cmor/blob/a246d1d0eb6cf5f5f42920d951c0564e06233b8a/Src/cmor_axes.c#L1240-L1255
https://github.com/PCMDI/cmor/blob/a246d1d0eb6cf5f5f42920d951c0564e06233b8a/Src/cmor_axes.c#L1262-L1265

**Comment by taylor13** [comment]
My mistake ... don't know why I didn't correctly interpret the logic in the case of a min/max = 0.  Obviously there is need for any action.

**Pull request merged**
