### PR TITLE
read tracking_prefix from tables and prepend to UUID

### PR DESCRIPTION
**Pull request by TobiasWeigel**

### CODE REVIEW

**Comment by TobiasWeigel** [comment]
Merge pull.

**Comment by doutriaux1** [comment]
@TobiasWeigel do you still want this merged into master? You closed the PR so I'm not quite sure if it was accidental or on purpose.

**Comment by TobiasWeigel** [comment]
Hello Charles.
yes, right now it was an accident - but I want to merge this quite soon. We are going to test the changes first, afterwards I will open another pull request.
Thanks, Tobias

**Comment by doutriaux1** [comment]
@dnadeau4 can you please review this then since you are currently working on the table revamping? Thanks.

**Comment by dnadeau4** [comment]
merge done!

Denis

**Pull request merged**
