### PR TITLE
Set grid_vertices dimensions for one dimensional grid

### PR DESCRIPTION
**Pull request by wachsylon**
An unstructured grid registered via cmor_grid may have only one dimension. In that case, the vertices_latitude and vertices_longitude variables of that grid have wrong dimensions. This is debugged with this patch.

### CODE REVIEW

**Comment by wachsylon** [comment]
See #357

**Comment by doutriaux1** [comment]
thanks @wachsylon , same here will review and merge tomorrow

**Comment by doutriaux1** [comment]
@wachsylon can you please add a test or simply provide a simple (python/C/Fortran) code to make sure we fixed this correctly? Thanks!

**Comment by wachsylon** [comment]
Please find a test file in
https://swiftbrowser.dkrz.de/tcl_objects/2018-07-08T08:23:43Z/r_a3177941fb1821e7c76f32d945f090e6971c70a3/w_/dkrz_5c667751-d212-48fd-96a1-6c02f7c7a919/CMOR_test/0/

**Comment by doutriaux1** [comment]
moved branch to pcmdi repo please add test at: https://github.com/PCMDI/cmor/pull/379

**Comment by doutriaux1** [comment]
@wachsylon I get access denied on your file, also I would prefer a script thatI can add to the test suite

**Pull request closed without merging**
