### PR TITLE
PR to resolve some conflicts since last merging into PrePARE

### PR DESCRIPTION
**Pull request by glevava**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@glevava I took over CMOR from @dnadeau4 for the time being, I will consult with @taylor13 and possibly @dnadeau4 before merging this in. Thanks for this!

**Comment by glevava** [comment]
Yes. You may avoid changes to the print statement if you want. I just modify messages for easier search in output files using grep commands lines.

**Comment by doutriaux1** [comment]
@glevava is this this finished or not? Things keep being added to the PR. I'm quite confiused about the status of this PR.

**Comment by glevava** [comment]
My PR started in May. Since we needed lot of PrePARE changes to be able to publish CMIP6 data. Sorry about recent changes. They are necessary to publish climatology data. But this can be part of another PR if you prefer. I must admit I'm not thinking about the PR anymore, I made the changes on my fork and I forgot my commits are propagated on the old PR.

**Comment by glevava** [comment]
Ok

**Comment by dnadeau4** [comment]
merge with #358

**Pull request closed without merging**
