### PR TITLE
Update CMIP6 tables to 01.00.31

### PR DESCRIPTION
**Pull request by mauzey1**
The OSX Python 2.7 tests failed due to an error during code checkout.  The Python 2.7 tests passed when I ran them on my macbook.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@mauzey1 it failed on mac

**Comment by mauzey1** [comment]
@doutriaux1 All tests have passed now.

**Comment by dnadeau4** [comment]
@doutriaux1 I cannot merge this since I am not in the PCMDI group. 😏

**Comment by durack1** [comment]
@dnadeau4 we have a seat problem with the PCMDI organization, as @zshaheen has left the project I've shuffled his seat for yours - you should now have access

**Comment by dnadeau4** [comment]
@mauzey1 you can merge this PR. Thanks!

**Comment by dnadeau4** [comment]
@durack1 thanks!

**Pull request merged**
