### PR TITLE
Throw exception if not enough data is passed to cmor.write in Python

### LINKED ISSUE #485: not passing enough times as data passes
ntimes_written=2

but passing enough data only for 1 time should not work and right now it does

### PR DESCRIPTION
**Pull request by mauzey1**
Resolves #485

This change checks the amount of data being passed to cmor.write in Python if it is the expected amount for the amount of time passed (either by setting ntimes_passed or passing time values).  It will throw an exception if the amount is lower than expected (or if ntimes_passed is negative).

I also added a test to see if the exception is being thrown.

As for Fortran, it looks like it already handles this issue.
https://github.com/PCMDI/cmor/blob/8a48023d6456b596df5f0a1a9440bc3fe4d2634c/Src/cmor_fortran_interface.f90#L1032-L1037

### CODE REVIEW

**Comment by mauzey1** [comment]
@doutriaux1 It is currently named test_python_CMIP6_CV_not_enough_data.py since the CMIP6_CV tests are the only Python tests currently being used in CI.  https://github.com/PCMDI/cmor/pull/493 will add the other Python tests back in.

I will get started on a Fortran test.

**Comment by mauzey1** [comment]
@doutriaux1 Is there a way to catch an error in Fortran?  If cmor_write has an error it will return CMOR_CRITICAL, but I want to catch the "not enough data" message.

**Comment by doutriaux1** [comment]
@mauzey1 I was dealing with these sort of things back here: https://github.com/PCMDI/cmor/pull/387/files

Let me know if it does not help you.

**Comment by mauzey1** [comment]
@doutriaux1 I am not sure what to take from that.

Another issue with the Fortran test is that the error uses CMOR_CRITICAL, which exits the program at cmor_handle_error before cmor_write can return the error flag.

**Comment by mauzey1** [comment]
@doutriaux1 I have moved the not-enough-data test from the CMIP6 CV tests to the Python tests in the Makefile.

**Pull request merged**
