### PR TITLE
fix #366

### LINKED ISSUE #366: Should we use cmor 3.3.3 already?
Hi,

Our ece2cmor3 package which relies on cmor is broken. We wonder whether we should update to the following cmor package: `linux-64/cmor-2018.06.28.master.npy1.14-py27h9ac9557_0` as it is not marked as `main`? Or do we better wait (is it coming in a few days for instance?).

A second question we have: Any idea when the cmor tables will be based on data request 01.00.26? Is this soon or is there always a bit longer delay?

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by taylor13** [comment]
I have no idea why this bit of coding is needed, so I don't feel qualified to review it.

**Comment by doutriaux1** [comment]
it's a test, you probably asked for it ;)

**Comment by taylor13** [comment]
What error message does the user see if CMOR is unable to open the table?

**Comment by durack1** [comment]
@doutriaux1 is this a dead PR or should it be updated and merged?

**Comment by doutriaux1** [comment]
@durack1 just never been merged in, it's an additional test. @mauzey1 feel free to merge in if you approve.

**Comment by doutriaux1** [comment]
@mauzey1 thanks for doing this!

**Comment by mauzey1** [comment]
@doutriaux1 Should this test be using the BaseCVsTest class like the other CMIP6_CV tests?

**Comment by doutriaux1** [comment]
@mauzey1 no this one does not need to, it just loads the tables and see if it works, doesn't need all the bells and whistles.

**Pull request merged**
