### PR TITLE
Add Python 3 support to CMOR

### LINKED ISSUE #282: Update cmor3 for python3
Just to mention that I have been able to successfully run cmor3 with a new anaconda installation of software (python=2.7) - I plan to create a python=3.6 version of my cmor3 based software removing packages that only exist in python2*, this means removing dependancies on packages like cdms2 that I think are only python2* currently (some packages are only currently supported in python3 like xesmf that I need to utilise for regridding).
It was easy to setup my cmor3 input file with sensible values and no issues with items like license last time. Previously I had to establish my own python environment, but now anaconda appears to be flexible enough for most applications.
Thanks for the great work.

### PR DESCRIPTION
**Pull request by mauzey1**
Fix #282

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 this is huge!!

**Comment by doutriaux1** [comment]
@mauzey1 looks good now. I'm approving

**Comment by doutriaux1** [comment]
@mauzey1 if you can't merge (because of pending statuses) let me know I wil ldo it for you.

**Comment by durack1** [comment]
When this is done, it's very much worthy of a full MINOR release increment to 3.5.0

**Pull request merged**
